feat(Ray): add naice sphere intersection
arthur-targaryen/ray-tracing-rust pull request #5
Opened 2021-04-19 17:44 UTC by arthur-targaryen

2021-04-19 18:20 UTC, Hasenn requested changes
Please add some comments explaining your math (even if its just the wikipedia link)

2021-04-19 18:20 UTC, Hasenn commented on src/ray.rs
> +        let a = self.direction.dot(&self.direction);
what's a, b and c ? do they have an interpretation ?
a looks likes the norm of direction squared, you could call it `length_squared` maybe

2021-04-19 18:20 UTC, Hasenn commented on src/ray.rs
> +        let a = self.direction.dot(&self.direction);
if the ray is normalized, wouldn't this be always 1 ?

2021-04-19 18:20 UTC, Hasenn commented on src/ray.rs
> +        let c = oc.dot(&oc) - radius * radius;
a comment explaining what's going on, what polynomial you are manipulating, or maybe a wikipedia link would be very welcome

2021-04-19 18:20 UTC, Hasenn commented on src/ray.rs
> +        let discriminant = b * b - 4.0 * a * c;
it looks like you used https://en.wikipedia.org/wiki/Line%E2%80%93sphere_intersection
if you did, put a link in there

2021-04-19 18:27 UTC, Hasenn commented on src/ray.rs
> +        if self.hit_sphere(&Point3::new(0.0, 0.0, -1.0), 0.5) {
If i'm raytracing i might want to know where the ray intersects the sphere, so maybe `hit (...) -> Option<HitData>` and `try_hit : (...) -> bool` would be a more sensible api ?

2021-04-19 20:18 UTC, merged

2021-04-25 13:32 UTC, arthur-targaryen commented on src/ray.rs
> +    fn hit_sphere(&self, center: &Point3, radius: f64) -> bool {
Done! I added a `Sphere` struct in 14219002dddc951f818f4af6d1595d790bbe346d.

2021-04-25 13:35 UTC, arthur-targaryen commented on src/ray.rs
> +        if self.hit_sphere(&Point3::new(0.0, 0.0, -1.0), 0.5) {
Changed this in c18d97ec341a632a49a64f92d80868ebfba9e053 by adding `Hittable` trait, with `Hittable::try_hit()`.

2021-04-25 13:36 UTC, arthur-targaryen commented on src/ray.rs
> +        let discriminant = b * b - 4.0 * a * c;
I made it clearer by adding the link to the `Sphere::try_hit()` documentation (/a7358bd304011b42c29595614743492682e2006e) where this code has been moved. Should help understand `a`, `b` and `c` meanings.